# The containers that need to run.
services:
  webshop:
    # The name of the image (`docker build --tag=webshop:0.1.0`)
    image: webshop:0.1.0
    # If this service uses an image from source, this is the local directory containing its Dockerfile.
    build:
      context: .
      args:
        - POSTGRES_USER
        - POSTGRES_DB
        - POSTGRES_PASSWORD
    ports:
      - 80:8000
    networks:
      - webshop_network
    depends_on:
      - database
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    networks:
      - webshop_network

networks:
  webshop_network:
